version: "3.3"

services:
  database:
    image: mysql:5.7
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - my-money
    restart: always

volumes:
  mysql:
    driver: local

networks:
  my-money:
    driver: bridge
