# -*- coding: utf-8 -*-
"""dicionarios

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SDTWHpIeorp5bhSdzjP3zXT82cs8CBBB
"""

#dicionarios, em outras linguagens, são mapas
#tipo chave:valor(es)
#{}
#qualquer tipo de dado
#não tem chave repetida


paises = {"br":"Brasil", "eua":"Estados Unidos", "py":"Paraguai"}
print(paises)

paises = dict(br="Brasil", eua="Estados Unidos", py="Paraguai")
(print(paises))

outro = {}.fromkeys(["a","b"],["desconhecido","hum"])
print(outro)

#acessando
paises["br"] #index

paises.get("br") #por .get()
paises.get("ru","Não encontrado") #o segundo parametro é o valor padrão para o False

print("br" in paises) #verificando se existe

#tuplas como chave de dicionário é um bom exemplo, já q elas não mudam
localidade = {(35.0995, 39.6917): "Escritório em tókio"}

#append em dict
receita = {"jan":350, "fev":400, "mar":200}
receita["abr"] = 350
print(receita)

novo_dado = {"mai": 500}
receita.update(novo_dado)
print(receita)

#atualizando
receita["abr"] = 600
print(receita)

novo_dado = {"mai": 900}
receita.update(novo_dado)
print(receita)

#removendo
receita.pop("mar") #por padrão retorna os valores a serem excluidos
receita

del receita["abr"]
receita

#para carrinho de compras
produto = {"nome":"Play 4", "quantidade":1, "Preço":1500.00}
produto

#zerar o dicionário
produto.clear()
produto

#deep copy
novo = produto.copy()
novo["oi"] = 4
produto, novo

#shalow copy
novo = produto
novo["d"] = 5
novo, produto