# -*- coding: utf-8 -*-
"""listas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yBjtP-yw6OVvAn_iE3tddbnkUg_iNaBh
"""

'''
Listas são dinâmicas e aceitam qualquer tipo de dado

-Dinâmico: Não tem tamanho fixo..   
-Qualquer: Aceita todo tipo de dado

Representadas por colchetes []
'''

lista1 = [1,99,4,5,7,8]

lista2 = ["L","u","c","a","s"]

lista3 = []

lista4 = list(range(11))

lista5 = list("vanessa")

#Ordenar lista
lista5.sort()
lista5

#Numero de ocorrencias numa lista
lista5.count("a")

#Adicionar elementos numa lista
#Um elemento por vez..
lista4.append("hum")
lista4

lista4.append(list("oi"))
lista4

#Adicionar vários elementos por vez
#Não aceita valor unico, só os iteráveis
lista1.extend([123,44,5])
lista1

#Adicionar elemento informando o local
#Empura elementos pros lados, não substitui
lista1.insert(2, 2) #local, dado
lista1

#listas podem se somar que nem o extend
lista6 = lista1+lista2
lista6

#inverter a lista
lista6.reverse()
lista6

#copiar listas (deep copy -> copia duas de forma independente)
lista7 = lista2.copy()
lista7

#shalow copy (uma ligada a outra)
lista = list(range(-1,5))
nova = lista
nova.append(4)
nova, lista

#tamanho da lista
len(lista7)

#remover o elemento da lista
#retorna por texto qual elemento a ser retirado
#os elementos se deslocam
lista2.pop()
lista2.pop(0)

lista2

#zerar a lista
lista6.clear()
lista6

#multiplicar lista
lista6.extend(3*"oi")
lista6

#converter string para lista, separando os elemtos por espaço em padrão, ou pode definir o separador
tradução = "AquiJás O Arruaceiro"
tradução.split()

tradução = "AquiJás,O,Arruaceiro"
lista8 = tradução.split(",")

#converter lista para string
'-'.join(lista8) #define o elemento que ficará nos lugares das virgulas que separam os elementos da lista

#"--"

#         0        1         2
cores = ["Azul","Amarelo","Vermelho"]
cores[0]
cores[-1]

#Iterando sobre listas
soma = 0
for i in lista1:
  print(i)
  soma += i

print(soma)

carrinho = [] 
produto = ""
while produto != "sair":
  produto = input()
  if produto != "sair":
    carrinho.append(produto)

carrinho

#Encontrar o indice do elemento na lista
numeros = list(range(5,11))
numeros.index(6)

#por range presente
numeros.index(6,3) #define o valor de partida
numeros.index(6,3,5) #define o valor de partida e final

#slice
lista = list(range(1,5))
print(lista[::]) #todos
print(lista[2::]) #começo 
print(lista[2:3:]) #começo, fim
print(lista[0:5:2]) #passo

#"--"

sum(lista)
max(lista)
min(lista)

#"--"

#transformar lista em tupla
lista = tuple(lista)
lista

#desenpacotamento da lista (mesmo numero de len e de variaveis)
lista = [0,1,2]
num1, num2, num3 = lista
num1, num2, num3