# -*- coding: utf-8 -*-
"""while

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FScjZmFyz6s-JQkah5p7d0MHLBaw52HI
"""

'''
while expressao_booleana:
  //executa

repete enquanto for verdadeiro
sempre tomar cuidado com os critérios de parada !
'''


numero = 1

while numero < 10:
  print(numero)
  numero += numero