# -*- coding: utf-8 -*-
"""mapas (dict())

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fqj0OpU0-jZ8NT-nG6qJh5xwiZKztI_G
"""

receita = {"jan":200, "fev":500}

for i in receita:
  print(i)
  print(receita[i])

receita.keys()

receita.values()

#operações matemáticas
sum(receita.values())
min(receita.values())
max(receita.values())
len(receita)