CREATE TABLE bank_accounts (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  UUID VARCHAR(36) NOT NULL,
  USER_ID INT(11) NOT NULL,
  AGENCY_NUMBER VARCHAR(255) NOT NULL,
  ACCOUNT_NUMBER VARCHAR(255) NOT NULL,
  BANK_NAME VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY UUID (UUID),
  FOREIGN KEY (USER_ID) REFERENCES users(ID)
)

