CREATE TABLE users (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  UUID VARCHAR(36) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  DELETED_AT TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY UUID (UUID)
)

