# -*- coding: utf-8 -*-
"""range()

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1srZ9DnYUYGVraWrJretuD0rZiQURPxsS
"""

''' 
ranges são sequencias numericas definidas 

range(valor_parada) 0->valor_parada

range(valor_inicio, valor_parada) valor_inicio->valor_parada

range(valor_inicio, valor_parada, passo) valor_inicio, passa x até ->valor_parada

'''

for i in range(11):
  print(i)

for i in range(5,7):
  print(i)
  
for i in range(15,5,-5):
  print(i)

lista = list(range(5,10))
print(lista)