# -*- coding: utf-8 -*-
"""None

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZCs361ch48vFZmWJvqtqdFow-1y1Hmuk
"""

#tipo sem tipo
#tipo vazio
#criado para poder receber outros valores no futuro

#sempre considerado como False

numeros = None
print(type(numeros))