# -*- coding: utf-8 -*-
"""break

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ae42nODo9jm2trMisVIvNzz4AMMTFYMB
"""

'''
Sair de loops de forma forçada
'''
for i in range(1,11):
  if i == 6:
    break
  else:
    print(i)

while True:
  comando = input("Digite sair para sair: ")
  if comando == "sair":
    break